// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Base64} from "@openzeppelin/contracts/utils/Base64.sol";
import {Strings} from "@openzeppelin/contracts/utils/Strings.sol";

interface IWhaleRenderer {
    function render(uint256 tokenId, uint256 seed, uint64 activatedAt, uint256 weight, uint32 activations)
        external
        pure
        returns (string memory);

    function tierOf(uint256 tokenId, uint256 seed) external pure returns (uint8);
}

/// @title WhaleRenderer
/// @notice Draws the whales. Every pixel comes out of this contract -- there is
///         no server, no IPFS pin, no metadata that can be swapped out later.
///
/// @dev The whale is a 24x16 grid packed into two words per layer, generated by
///      `script/genart.js`. Colours come from the rarity tier; the accents come
///      from the token's own hash, so no two whales in a tier look alike.
contract WhaleRenderer is IWhaleRenderer {
    using Strings for uint256;

    uint256 internal constant W = 24;
    uint256 internal constant H = 16;

    // Layer bitmaps: rows 0-7 in _HI, rows 8-15 in _LO, 24 bits per row,
    // column 0 in the most significant bit of each row.
    uint256 internal constant BODY_HI = 0x00000000000000000003fc000fff833fffe37ffff3dffffb;
    uint256 internal constant BODY_LO = 0xffffff800000000000000000000000000000000000000000;
    uint256 internal constant BELLY_HI = 0x000000000000000000000000000000000000000000000000;
    uint256 internal constant BELLY_LO = 0x0000007ffffb7f0ff33f0fe30f8f8303fc00000000000000;
    uint256 internal constant FIN_HI = 0x000000000000000000000000000000000000000000000000;
    uint256 internal constant FIN_LO = 0x00000000000000f00000f000007000000000000000000000;
    uint256 internal constant EYE_HI = 0x000000000000000000000000000000000000000000200000;
    uint256 internal constant EYE_LO = 0x000000000000000000000000000000000000000000000000;
    uint256 internal constant SPOUT_HI = 0x03400004a000034000000000000000000000000000000000;
    uint256 internal constant SPOUT_LO = 0x000000000000000000000000000000000000000000000000;

    struct Palette {
        string waterTop;
        string waterBottom;
        string body;
        string belly;
        string fin;
        string accent;
    }

    /// @inheritdoc IWhaleRenderer
    function tierOf(uint256 tokenId, uint256 seed) public pure returns (uint8) {
        uint256 roll = uint256(keccak256(abi.encode(seed, tokenId))) % 1000;
        if (roll == 0) return 4; // leviathan,      1 in 1000
        if (roll < 25) return 3; // abyss dweller,  2.4%
        if (roll < 125) return 2; // twilight diver, 10%
        if (roll < 425) return 1; // reef cruiser,   30%
        return 0; //               surface swimmer, 57.5%
    }

    function tierName(uint8 tier) public pure returns (string memory) {
        if (tier == 4) return "Leviathan";
        if (tier == 3) return "Abyss Dweller";
        if (tier == 2) return "Twilight Diver";
        if (tier == 1) return "Reef Cruiser";
        return "Surface Swimmer";
    }

    /// @notice Flavour depth in metres -- deeper tier, darker water.
    function depthOf(uint8 tier, uint256 tokenId, uint256 seed) public pure returns (uint256) {
        uint256 jitter = uint256(keccak256(abi.encode("depth", seed, tokenId)));
        if (tier == 4) return 10_900;
        if (tier == 3) return 4_000 + (jitter % 2_000);
        if (tier == 2) return 1_000 + (jitter % 1_500);
        if (tier == 1) return 200 + (jitter % 500);
        return 5 + (jitter % 150);
    }

    function paletteOf(uint8 tier) public pure returns (Palette memory) {
        if (tier == 4) {
            return Palette("#01040c", "#000000", "#e8f4ff", "#a8c8e8", "#5a86b8", "#ffd166");
        }
        if (tier == 3) {
            return Palette("#020814", "#000205", "#12385e", "#1d5688", "#0b2440", "#57e6c9");
        }
        if (tier == 2) {
            return Palette("#04162e", "#010812", "#1d5f9c", "#2f86cd", "#123f6b", "#7fd4ff");
        }
        if (tier == 1) {
            return Palette("#062a4d", "#031a33", "#2a7fbf", "#4aa8e0", "#1b5c8f", "#9be7ff");
        }
        return Palette("#0a3b63", "#052744", "#3d97cf", "#6fc2ea", "#2b74a6", "#d8f4ff");
    }

    // --- Rendering --------------------------------------------------------

    /// @inheritdoc IWhaleRenderer
    function render(uint256 tokenId, uint256 seed, uint64 activatedAt, uint256 weight, uint32 activations)
        external
        pure
        returns (string memory)
    {
        string memory image = seed == 0 ? _dormantWaters() : _whale(tokenId, seed, activatedAt != 0);
        string memory json = string.concat(
            '{"name":"Whale #',
            tokenId.toString(),
            '","description":"One of 1000 pixel whales. Feed the whale. Haul the Trench. Own the tide.","image":"data:image/svg+xml;base64,',
            Base64.encode(bytes(image)),
            '","attributes":',
            _attributes(tokenId, seed, activatedAt, weight, activations),
            "}"
        );
        return string.concat("data:application/json;base64,", Base64.encode(bytes(json)));
    }

    function _attributes(uint256 tokenId, uint256 seed, uint64 activatedAt, uint256 weight, uint32 activations)
        internal
        pure
        returns (string memory)
    {
        string memory status = string.concat(
            '{"trait_type":"Status","value":"',
            activatedAt == 0 ? "Dormant" : "Fed",
            '"},{"trait_type":"Activations","display_type":"number","value":',
            uint256(activations).toString(),
            "}"
        );

        if (seed == 0) {
            return string.concat('[{"trait_type":"Tier","value":"Unrevealed"},', status, "]");
        }

        uint8 tier = tierOf(tokenId, seed);
        return string.concat(
            '[{"trait_type":"Tier","value":"',
            tierName(tier),
            '"},{"trait_type":"Depth","display_type":"number","value":',
            depthOf(tier, tokenId, seed).toString(),
            '},{"trait_type":"Weight","value":"',
            _multiplier(weight),
            'x"},',
            status,
            "]"
        );
    }

    /// @dev Weight is basis points of 1.00x; render it as e.g. "2.15".
    function _multiplier(uint256 weight) internal pure returns (string memory) {
        uint256 whole = weight / 10_000;
        uint256 frac = (weight % 10_000) / 100;
        return string.concat(whole.toString(), ".", frac < 10 ? "0" : "", frac.toString());
    }

    function _whale(uint256 tokenId, uint256 seed, bool fed) internal pure returns (string memory) {
        uint8 tier = tierOf(tokenId, seed);
        Palette memory p = paletteOf(tier);
        uint256 hash = uint256(keccak256(abi.encode("art", seed, tokenId)));

        bytes memory pixels;
        for (uint256 y = 0; y < H; y++) {
            for (uint256 x = 0; x < W; x++) {
                string memory fill = _fillAt(p, hash, y, x);
                if (bytes(fill).length == 0) continue;
                pixels = abi.encodePacked(
                    pixels,
                    '<rect x="',
                    x.toString(),
                    '" y="',
                    y.toString(),
                    '" width="1" height="1" fill="',
                    fill,
                    '"/>'
                );
            }
        }

        return string(
            abi.encodePacked(
                '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 16" width="480" height="320" shape-rendering="crispEdges">',
                '<defs><linearGradient id="w" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="',
                p.waterTop,
                '"/><stop offset="1" stop-color="',
                p.waterBottom,
                '"/></linearGradient></defs>',
                '<rect width="24" height="16" fill="url(#w)"/>',
                _bubbles(hash, p.accent),
                pixels,
                fed ? _glow(p.accent) : "",
                "</svg>"
            )
        );
    }

    /// @dev Returns the colour for a pixel, or an empty string for open water.
    function _fillAt(Palette memory p, uint256 hash, uint256 y, uint256 x)
        internal
        pure
        returns (string memory)
    {
        if (_lit(EYE_HI, EYE_LO, y, x)) return p.accent;
        if (_lit(SPOUT_HI, SPOUT_LO, y, x)) return p.accent;
        if (_lit(FIN_HI, FIN_LO, y, x)) return p.fin;
        if (_lit(BELLY_HI, BELLY_LO, y, x)) return p.belly;
        if (_lit(BODY_HI, BODY_LO, y, x)) {
            // Scatter a few barnacles across the back, seeded per whale.
            if (y < 8 && uint256(keccak256(abi.encode(hash, y, x))) % 23 == 0) return p.fin;
            return p.body;
        }
        return "";
    }

    function _lit(uint256 hi, uint256 lo, uint256 y, uint256 x) internal pure returns (bool) {
        uint256 word = y < 8 ? hi : lo;
        uint256 row = (word >> (24 * (7 - (y % 8)))) & 0xFFFFFF;
        return (row >> (W - 1 - x)) & 1 == 1;
    }

    /// @dev Three bubbles rising off the whale, placed by the token hash.
    function _bubbles(uint256 hash, string memory accent) internal pure returns (string memory) {
        bytes memory out;
        for (uint256 i = 0; i < 3; i++) {
            uint256 h = uint256(keccak256(abi.encode(hash, "bubble", i)));
            out = abi.encodePacked(
                out,
                '<circle cx="',
                (h % 22 + 1).toString(),
                '" cy="',
                ((h >> 8) % 14 + 1).toString(),
                '" r="0.',
                ((h >> 16) % 3 + 2).toString(),
                '" fill="',
                accent,
                '" opacity="0.',
                ((h >> 24) % 3 + 1).toString(),
                '"/>'
            );
        }
        return string(out);
    }

    /// @dev A fed whale carries a halo. Dormant whales swim dark.
    function _glow(string memory accent) internal pure returns (string memory) {
        return string.concat(
            '<rect x="0" y="0" width="24" height="16" fill="none" stroke="',
            accent,
            '" stroke-width="0.4" opacity="0.75"/>'
        );
    }

    /// @dev Pre-reveal art: open water, no whale in sight.
    function _dormantWaters() internal pure returns (string memory) {
        return
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 16" width="480" height="320" shape-rendering="crispEdges"><defs><linearGradient id="w" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#0a3b63"/><stop offset="1" stop-color="#01040c"/></linearGradient></defs><rect width="24" height="16" fill="url(#w)"/><text x="12" y="9" font-family="monospace" font-size="1.6" fill="#7fd4ff" text-anchor="middle" opacity="0.8">deep water</text></svg>';
    }
}
